apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rsw3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hmdf-tenant/rhtap-demo-app/hacbs-test-project-rsw3@sha256:3ea20e86dfb51e78e23aed5cee12565a6b9b48777d56760b5ff2b1589f149b07
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
